import { NextRequest, NextResponse } from "next/server";

export async function POST(request: NextRequest) {
  try {
    const { itinerary, title = "Travel Itinerary" } = await request.json();

    if (!itinerary) {
      return NextResponse.json(
        { error: "Itinerary content is required" },
        { status: 400 }
      );
    }

    // Format itinerary untuk HTML
    const formattedContent = itinerary
      .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
      .replace(/\n/g, "<br>")
      .replace(
        /^# (.*$)/gm,
        '<h1 style="color: #1e40af; font-size: 22px; margin: 20px 0 15px 0;">$1</h1>'
      )
      .replace(
        /^## (.*$)/gm,
        '<h2 style="color: #2563eb; font-size: 18px; margin: 15px 0 10px 0;">$2</h2>'
      )
      .replace(
        /^### (.*$)/gm,
        '<h3 style="color: #3b82f6; font-size: 16px; margin: 12px 0 8px 0;">$1</h3>'
      )
      .replace(
        /Rp\s*([\d,.]+)/g,
        '<span style="background: #fef3c7; padding: 2px 4px; border-radius: 3px; font-weight: 600;">Rp $1</span>'
      );

    const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
    
    body {
      font-family: 'Inter', Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      background: #ffffff;
    }
    
    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 2px solid #e5e7eb;
    }
    
    .title {
      color: #1e40af;
      font-size: 28px;
      font-weight: 700;
      margin-bottom: 10px;
    }
    
    .subtitle {
      color: #6b7280;
      font-size: 14px;
      margin-bottom: 20px;
    }
    
    .content {
      font-size: 14px;
    }
    
    h1 {
      color: #1e40af;
      font-size: 22px;
      margin: 25px 0 15px 0;
      padding-bottom: 8px;
      border-bottom: 1px solid #e5e7eb;
    }
    
    h2 {
      color: #2563eb;
      font-size: 18px;
      margin: 20px 0 12px 0;
    }
    
    h3 {
      color: #3b82f6;
      font-size: 16px;
      margin: 16px 0 10px 0;
    }
    
    p {
      margin: 12px 0;
    }
    
    ul, ol {
      margin: 12px 0;
      padding-left: 24px;
    }
    
    li {
      margin: 6px 0;
    }
    
    .budget {
      background: #f3f4f6;
      padding: 15px;
      border-radius: 8px;
      margin: 20px 0;
      border-left: 4px solid #10b981;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      color: #6b7280;
      font-size: 12px;
    }
    
    .highlight {
      background: #fef3c7;
      padding: 2px 6px;
      border-radius: 4px;
      font-weight: 600;
    }
    
    .section {
      margin-bottom: 30px;
      page-break-inside: avoid;
    }
    
    @media print {
      body {
        padding: 20px;
      }
      .no-print {
        display: none;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1 class="title">${title}</h1>
    <p class="subtitle">
      Generated by Travel AI Planner • ${new Date().toLocaleDateString(
        "id-ID",
        {
          weekday: "long",
          year: "numeric",
          month: "long",
          day: "numeric",
        }
      )}
    </p>
  </div>
  
  <div class="content">
    ${formattedContent}
  </div>
  
  <div class="footer">
    <p>✨ Planned with AI • Travel AI Planner</p>
    <p>https://travel-ai-planner.vercel.app</p>
  </div>
</body>
</html>`;

    // Untuk versi simple tanpa puppeteer (hanya return HTML):
    return NextResponse.json({
      success: true,
      html: htmlContent,
      title: title,
      message: "HTML content generated successfully",
    });
  } catch (error) {
    console.error("PDF API Error:", error);
    return NextResponse.json(
      { error: "Failed to generate PDF content" },
      { status: 500 }
    );
  }
}
