"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";

export default function PrintPage() {
  const params = useParams();
  const [content, setContent] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Load from localStorage atau API
    const savedItinerary = localStorage.getItem(`itinerary_${params.id}`);
    if (savedItinerary) {
      setContent(savedItinerary);
    }
    setLoading(false);

    // Auto print setelah load
    setTimeout(() => {
      window.print();
    }, 1000);
  }, [params.id]);

  if (loading) {
    return <div className="p-8">Loading...</div>;
  }

  return (
    <div className="p-8 max-w-4xl mx-auto print:p-0">
      <div className="text-center mb-8 print:mb-4">
        <h1 className="text-3xl font-bold text-blue-800 mb-2">
          Travel Itinerary
        </h1>
        <p className="text-gray-600">
          Generated by Travel AI Planner •{" "}
          {new Date().toLocaleDateString("id-ID")}
        </p>
      </div>

      <div className="prose prose-lg max-w-none">
        <div className="whitespace-pre-wrap">{content}</div>
      </div>

      <div className="mt-12 pt-8 border-t text-center text-sm text-gray-500 print:mt-8">
        <p>✨ Planned with AI • Travel AI Planner</p>
        <p className="mt-2">
          For best results, use "Save as PDF" in print dialog
        </p>
      </div>
    </div>
  );
}
