import jsPDF from "jspdf";
import { Itinerary, DayPlan } from "../types";

export async function generatePDF(itinerary: Itinerary): Promise<void> {
  const doc = new jsPDF();
  const { tripInput, days, budgetBreakdown } = itinerary;
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = margin;

  // Add title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text(
    `${days.length} Days in ${tripInput.destination}`,
    pageWidth / 2,
    yPosition,
    { align: "center" }
  );
  yPosition += 10;

  // Trip details
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const tripDetails = [
    `Dates: ${new Date(tripInput.startDate).toLocaleDateString()} - ${new Date(
      tripInput.endDate
    ).toLocaleDateString()}`,
    `Travelers: ${tripInput.travelers}`,
    `Budget: Rp ${(
      tripInput.budgetPerPerson * tripInput.travelers
    ).toLocaleString("id-ID")}`,
    `Travel Style: ${tripInput.travelStyle.join(", ")}`,
  ];

  tripDetails.forEach((detail) => {
    yPosition += 6;
    doc.text(detail, margin, yPosition);
  });

  yPosition += 15;

  // Days itinerary
  days.forEach((dayPlan: DayPlan, dayIndex: number) => {
    // Check if we need a new page
    if (yPosition > 250) {
      doc.addPage();
      yPosition = margin;
    }

    // Day header
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text(
      `Day ${dayPlan.day} - ${new Date(dayPlan.date).toLocaleDateString(
        "en-US",
        {
          weekday: "long",
          month: "short",
          day: "numeric",
        }
      )}`,
      margin,
      yPosition
    );
    yPosition += 8;

    // Activities
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    const activities = [
      { type: "morning", emoji: "🌅", title: "Morning" },
      { type: "lunch", emoji: "🍽️", title: "Lunch" },
      { type: "afternoon", emoji: "☀️", title: "Afternoon" },
      { type: "dinner", emoji: "🍽️", title: "Dinner" },
      { type: "evening", emoji: "🌙", title: "Evening" },
    ];

    activities.forEach(({ type, emoji, title }) => {
      const activity =
        dayPlan.activities[type as keyof typeof dayPlan.activities];
      if (!activity) return;

      // Check if we need a new page for this activity
      if (yPosition > 270) {
        doc.addPage();
        yPosition = margin;
      }

      yPosition += 6;
      doc.setFont("helvetica", "bold");
      doc.text(`${emoji} ${title}: ${activity.name}`, margin + 5, yPosition);

      yPosition += 4;
      doc.setFont("helvetica", "normal");

      // Split description into multiple lines if too long
      const descriptionLines = doc.splitTextToSize(
        activity.description,
        pageWidth - margin * 2 - 10
      );
      descriptionLines.forEach((line: string) => {
        yPosition += 4;
        doc.text(line, margin + 10, yPosition);
      });

      // Activity details
      yPosition += 4;
      doc.text(`⏱️ ${activity.duration}`, margin + 10, yPosition);

      if (activity.cost > 0) {
        yPosition += 4;
        doc.text(
          `💰 Rp ${activity.cost.toLocaleString("id-ID")}`,
          margin + 10,
          yPosition
        );
      }

      yPosition += 8;
    });

    yPosition += 5;
  });

  // Budget Breakdown
  if (yPosition > 200) {
    doc.addPage();
    yPosition = margin;
  }

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Budget Breakdown", margin, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  const budgetCategories = [
    { label: "Accommodation", value: budgetBreakdown.accommodation },
    { label: "Food & Dining", value: budgetBreakdown.food },
    { label: "Activities", value: budgetBreakdown.activities },
    { label: "Transportation", value: budgetBreakdown.transportation },
    { label: "Miscellaneous", value: budgetBreakdown.miscellaneous },
  ];

  budgetCategories.forEach((category) => {
    doc.text(`${category.label}:`, margin + 5, yPosition);
    doc.text(
      `Rp ${category.value.toLocaleString("id-ID")}`,
      pageWidth - margin - 5,
      yPosition,
      { align: "right" }
    );
    yPosition += 6;
  });

  yPosition += 3;
  doc.setFont("helvetica", "bold");
  doc.text("Total:", margin + 5, yPosition);
  doc.text(
    `Rp ${budgetBreakdown.total.toLocaleString("id-ID")}`,
    pageWidth - margin - 5,
    yPosition,
    { align: "right" }
  );

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Generated by Travel Itinerary Planner • Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  // Save the PDF
  doc.save(
    `itinerary-${tripInput.destination.toLowerCase().replace(/\s+/g, "-")}.pdf`
  );
}
